#!/usr/bin/env php
<?php

use Studio24\HttpCacheClear\ClearHttpCacheCommand;
use Symfony\Component\Console\Application;

error_reporting(E_ALL ^ E_NOTICE);
ini_set('display_errors',true);

// Composer
$composer = [__DIR__ . '/../../vendor/autoload.php', __DIR__ . '/../../../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'];
foreach ($composer as $file) {
    if (file_exists($file)) {
        require_once $file;
        $composer = true;
    }
}
if (true !== $composer) {
    throw new \Exception('Cannot load Composer so cannot load dependencies');
}

$command = new ClearHttpCacheCommand();

$application = new Application();
$application->add($command);
$application->setDefaultCommand($command->getName(), true);
$application->run();

